Create Updated main.py
shaypheraddison/Baseball-Stat-Line-Calculator pull request #2
Opened 2023-11-09 18:06 UTC by shaypheraddison

Is this the kind of idea for creating a function? Or can it be simplified even further?

2023-11-09 20:17 UTC, resoluteCoder reviewed
I think this a great start and exactly what I was referring to. 

Let's do the same with accepting the input from the user that also returns the conversion in the proper type. Then store the two in variables which then get passed to the calc function

2023-11-10 04:11 UTC, shaypheraddison reviewed
Is this what you were saying? I feel like its a little excessive and don't know how to consolidate this much

2023-11-12 19:00 UTC, resoluteCoder reviewed
I like the addition of the list. Now you should be able to loop over each item and use the item in the print state of the input. This way you have one input statement but this will also require having to change how you declared/init your variables.

What you could do is look into dictionaries and use a single dict for all the values.

2023-11-13 22:39 UTC, shaypheraddison commented
I think I broke it. I had it working through the loop at one point today. it was even converting it to a float number, but now I keep getting an error when I have either float or int in front of the input. the error shows up after entering the first number too.

2023-11-14 21:21 UTC, resoluteCoder requested changes
Very nicely done a couple of improvements but otherwise very impressed! Let's keep it up!!

2023-11-14 21:21 UTC, resoluteCoder commented on Updated main.py
> +def get_user_input():
this code can be condensed to:
```python
stats = {}
labels = ["hits", "at-bats"] #the rest ...
for label in labels:
    str_value = input(f'Enter the number of {label}')
    stats[label] = int(str_value)
return stats
```

2023-11-14 21:21 UTC, resoluteCoder commented on Updated main.py
> +def calculate_and_display_slash_line(stats):
Let's change this from doing two things. Remember you want functions to do one thing (if you can help it)

try return the calculations in a format that can be sent do a `display_slash_line` function

2024-10-05 03:28 UTC, merged